/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainapp;

import java.sql.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;

/**
 *
 * @author santi
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form NewINTERFAZ
     */
    public interfaz() {
        initComponents();
    }

    public List<Integer> cod_bodegas_rutas = new ArrayList<>();
    Integer cantidad_1 = 0;
    Integer cantidad_2 = 0;
    Integer cantidad_3 = 0;
    Integer cantidad_4 = 0;
    Integer cantidad_5 = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jFrame1 = new javax.swing.JFrame();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        label7 = new java.awt.Label();
        campojpanel4 = new javax.swing.JTextField();
        label1 = new java.awt.Label();
        label6 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        label8 = new java.awt.Label();
        campojpanel1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        campojpanel2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        label9 = new java.awt.Label();
        campojpanel3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        label11 = new java.awt.Label();
        campojpanel5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jDialog1.setTitle("Pedidos Invalidos");

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 102, 255));
        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Algo esta mal con tu pedido");
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDialog2.setTitle("Pedidos Invalidos");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText(" No hay unidades suficientes");
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        label2.setText("Bienvenido Usurio");

        label3.setText(" A continuacion encontrara la lista de productos existentes ");

        label4.setName(""); // NOI18N
        label4.setText("para realizar pedidos, para ordenar uno de estos productos ");

        label5.setText("simplemente digite la cantidad que desea del mismo.");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        label7.setText("4. Botella jugo de cerdo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campojpanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(campojpanel4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setName(""); // NOI18N
        label1.setText("Cantidad");

        label6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label6.setName(""); // NOI18N
        label6.setText("Producto");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        label8.setText("1.Bolsa de leche de gato");

        campojpanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campojpanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campojpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(campojpanel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        label10.setText("2. Pollo verde");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campojpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(campojpanel2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        label9.setText("3. Niño azul");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campojpanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(campojpanel3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));

        label11.setText("5. Paleta miel de oveja");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(campojpanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label11, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addComponent(campojpanel5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Generar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                            .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        List<String> updates = new ArrayList<>();
        Map<Integer, List<String>> dictionary = new HashMap<Integer, List<String>>();

        Connection conn = null;
        Statement sentencia = null;
        ResultSet resultado = null;

        try { // Se carga el driver JDBC-ODBC
            Class.forName("oracle.jdbc.driver.OracleDriver");
        } catch (Exception e) {
            System.out.println("No se pudo cargar el driver JDBC");

        }

        try { // Se establece la conexi�n con la base de datos Oracle Express
            conn = DriverManager.getConnection("jdbc:oracle:thin:@LAPTOP-UNKNNU64:1521:xe", "gato", "gato");
            sentencia = conn.createStatement();
        } catch (SQLException e) {
            System.out.println("No hay conexi�n con la base de datos.");

        }
        try {
            resultado = sentencia.executeQuery("SELECT r.cod_bodega from registro r, TABLE(r.inventario) i where i.existencias>0 group by cod_bodega");
            while (resultado.next()) {
                List<String> listai = new ArrayList<>();
                dictionary.put(resultado.getInt("cod_bodega"), listai);
            }

            //Se cierra la conexion con la BD
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }

        try {
            if ((this.campojpanel1.getText().length() > 0) && (!this.campojpanel1.getText().equals("0"))) {
                updates.clear();
                
                cantidad_1 = Integer.parseInt(this.campojpanel1.getText());

                try {
                    resultado = sentencia.executeQuery("SELECT r.cod_bodega,i.cod_producto,i.existencias from registro r, TABLE(r.inventario) i WHERE i.cod_producto=1 and i.existencias>0 ");

                    while (resultado.next()) {

                        List<String> listatoEdit = dictionary.get(resultado.getInt("cod_bodega"));
                        int diferencia = cantidad_1 - resultado.getInt("existencias");

                        if (diferencia < 0) {
                            System.out.println("la diferencia en el resultado - es = " + diferencia);
                            listatoEdit.add(Integer.toString(cantidad_1) + " unidades del producto 1");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = " + Integer.toString(resultado.getInt("existencias") - cantidad_1)
                                    + " WHERE cod_producto=1";
                            System.out.println("valor u en caso - es = " + u);
                            updates.add(u);
                            cantidad_1 = 0;
                            break;
                        } else if (diferencia == 0) {
                            listatoEdit.add(Integer.toString(cantidad_1) + " unidades del producto 1");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=1";
                            System.out.println("valor u en caso = es = " + u);
                            updates.add(u);
                            cantidad_1 = 0;
                            break;
                        } else {

                            listatoEdit.add(Integer.toString(resultado.getInt("existencias")) + " unidades del producto 1");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=1";
                            System.out.println("valor u en caso = es = " + u);
                            updates.add(u);
                            cantidad_1 = cantidad_1 - resultado.getInt("existencias");
                        }

                        dictionary.put(resultado.getInt("cod_bodega"), listatoEdit);
                    }

                    if (cantidad_1 > 0) {
                        System.out.println("p1");
                        this.jDialog2.show();
                        jDialog2.setSize(300, 200);
                    } else {
                        for (String n : updates) {
                            System.out.println(n);
                            resultado = sentencia.executeQuery(n);
                        }
                    }

                } catch (SQLException e) {
                    System.out.println("Error: " + e.getMessage());
                }

            }
            if ((this.campojpanel2.getText().length() > 0) && (!this.campojpanel2.getText().equals("0"))) {
                updates.clear();
                cantidad_2 = Integer.parseInt(this.campojpanel2.getText());
                try {
                    resultado = sentencia.executeQuery("SELECT r.cod_bodega,i.cod_producto,i.existencias from registro r, TABLE(r.inventario) i WHERE i.cod_producto=2 and i.existencias>0 ");

                    while (resultado.next()) {

                        List<String> listatoEdit = dictionary.get(resultado.getInt("cod_bodega"));
                        int diferencia = cantidad_2 - resultado.getInt("existencias");
                        if (diferencia < 0) {
                            listatoEdit.add(Integer.toString(cantidad_2) + " unidades del producto 2");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = " + Integer.toString(resultado.getInt("existencias") - cantidad_2)
                                    + " WHERE cod_producto=2";
                            updates.add(u);
                            cantidad_2 = 0;
                            break;
                        } else if (diferencia == 0) {
                            listatoEdit.add(Integer.toString(cantidad_2) + " unidades del producto 2");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=2";
                            updates.add(u);
                            cantidad_2 = 0;
                            break;
                        } else {
                            listatoEdit.add(Integer.toString(resultado.getInt("existencias")) + " unidades del producto 2");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=2";
                            updates.add(u);
                            cantidad_2 = cantidad_2 - resultado.getInt("existencias");
                        }
                        dictionary.put(resultado.getInt("cod_bodega"), listatoEdit);
                    }
                    if (cantidad_2 > 0) {
                        System.out.println("p2");
                        this.jDialog2.show();
                        jDialog2.setSize(300, 200);
                    } else {
                        for (String n : updates) {
                            System.out.println(n);
                            resultado = sentencia.executeQuery(n);
                        }
                    }
                } catch (SQLException e) {
                    System.out.println("Error: " + e.getMessage());
                }

            }
            if ((this.campojpanel3.getText().length() > 0) && (!this.campojpanel3.getText().equals("0"))) {
                updates.clear();
                cantidad_3 = Integer.parseInt(this.campojpanel3.getText());
                try {
                    resultado = sentencia.executeQuery("SELECT r.cod_bodega,i.cod_producto,i.existencias from registro r, TABLE(r.inventario) i WHERE i.cod_producto=3 and i.existencias>0 ");

                    while (resultado.next()) {

                        List<String> listatoEdit = dictionary.get(resultado.getInt("cod_bodega"));
                        int diferencia = cantidad_3 - resultado.getInt("existencias");
                        if (diferencia < 0) {
                            listatoEdit.add(Integer.toString(cantidad_3) + " unidades del producto 3");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = " + Integer.toString(resultado.getInt("existencias") - cantidad_2)
                                    + " WHERE cod_producto=3";
                            updates.add(u);
                            cantidad_3 = 0;
                            break;
                        } else if (diferencia == 0) {
                            listatoEdit.add(Integer.toString(cantidad_3) + " unidades del producto 3");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=3";
                            updates.add(u);
                            cantidad_3 = 0;
                            break;
                        } else {
                            listatoEdit.add(Integer.toString(resultado.getInt("existencias")) + " unidades del producto 3");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=3";
                            updates.add(u);
                            cantidad_3 = cantidad_3 - resultado.getInt("existencias");
                        }
                        dictionary.put(resultado.getInt("cod_bodega"), listatoEdit);
                    }
                    if (cantidad_3 > 0) {
                        System.out.println("p3");
                        this.jDialog2.show();
                        jDialog2.setSize(300, 200);
                    } else {
                        for (String n : updates) {
                            System.out.println(n);
                            resultado = sentencia.executeQuery(n);
                        }
                    }

                } catch (SQLException e) {
                    System.out.println("Error: " + e.getMessage());
                }

            }
            if ((this.campojpanel4.getText().length() > 0) && (!this.campojpanel4.getText().equals("0"))) {
                updates.clear();
                cantidad_4 = Integer.parseInt(this.campojpanel4.getText());
                try {
                    resultado = sentencia.executeQuery("SELECT r.cod_bodega,i.cod_producto,i.existencias from registro r, TABLE(r.inventario) i WHERE i.cod_producto=4 and i.existencias>0 ");

                    while (resultado.next()) {

                        List<String> listatoEdit = dictionary.get(resultado.getInt("cod_bodega"));
                        int diferencia = cantidad_4 - resultado.getInt("existencias");
                        if (diferencia < 0) {
                            listatoEdit.add(Integer.toString(cantidad_4) + " unidades del producto 4");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = " + Integer.toString(resultado.getInt("existencias") - cantidad_2)
                                    + " WHERE cod_producto=4";
                            updates.add(u);
                            cantidad_4 = 0;
                            break;
                        } else if (diferencia == 0) {
                            listatoEdit.add(Integer.toString(cantidad_4) + " unidades del producto 4");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=4";
                            updates.add(u);
                            cantidad_4 = 0;
                            break;
                        } else {
                            listatoEdit.add(Integer.toString(resultado.getInt("existencias")) + " unidades del producto 4");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=4";
                            updates.add(u);
                            cantidad_4 = cantidad_4 - resultado.getInt("existencias");
                        }
                        dictionary.put(resultado.getInt("cod_bodega"), listatoEdit);
                    }
                    if (cantidad_4 > 0) {
                        System.out.println("p4");
                        this.jDialog2.show();
                        jDialog2.setSize(300, 200);
                    } else {
                        for (String n : updates) {
                            System.out.println(n);
                            resultado = sentencia.executeQuery(n);
                        }
                    }
                } catch (SQLException e) {
                    System.out.println("Error: " + e.getMessage());
                }

            }
            if ((this.campojpanel5.getText().length() > 0) && (!this.campojpanel2.getText().equals("0"))) {
                updates.clear();
                cantidad_5 = Integer.parseInt(this.campojpanel5.getText());
                try {
                    resultado = sentencia.executeQuery("SELECT r.cod_bodega,i.cod_producto,i.existencias from registro r, TABLE(r.inventario) i WHERE i.cod_producto=5 and i.existencias>0 ");

                    while (resultado.next()) {

                        List<String> listatoEdit = dictionary.get(resultado.getInt("cod_bodega"));
                        int diferencia = cantidad_5 - resultado.getInt("existencias");
                        if (diferencia < 0) {
                            listatoEdit.add(Integer.toString(cantidad_5) + " unidades del producto 5");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = " + Integer.toString(resultado.getInt("existencias") - cantidad_5)
                                    + " WHERE cod_producto=5";
                            updates.add(u);
                            cantidad_5 = 0;
                            break;
                        } else if (diferencia == 0) {
                            listatoEdit.add(Integer.toString(cantidad_5) + " unidades del producto 5");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=5";
                            updates.add(u);
                            cantidad_5 = 0;
                            break;
                        } else {
                            listatoEdit.add(Integer.toString(resultado.getInt("existencias")) + " unidades del producto 5");
                            String u = "UPDATE TABLE(SELECT inventario FROM registro where cod_bodega="
                                    + Integer.toString(resultado.getInt("cod_bodega")) + ") SET existencias = 0 WHERE cod_producto=5";
                            updates.add(u);
                            cantidad_5 = cantidad_5 - resultado.getInt("existencias");
                        }
                        dictionary.put(resultado.getInt("cod_bodega"), listatoEdit);
                    }
                    if (cantidad_5 > 0) {
                        System.out.println("p5");
                        this.jDialog2.show();
                        jDialog2.setSize(300, 200);
                    } else {
                        for (String n : updates) {
                            System.out.println(n);
                            resultado = sentencia.executeQuery(n);
                        }
                    }
                    conn.commit();
                    conn.close();
                } catch (SQLException e) {
                    System.out.println("Error: " + e.getMessage());
                }

            }

            for (int n : dictionary.keySet()) {
                if (dictionary.get(n).size() > 0) {
                    System.out.println("La wea esta en el for");
                    System.out.println("esto vale n " + n);
                    System.out.println("esto es dictionary " + dictionary.keySet());
                    this.cod_bodegas_rutas.add(n);
                }
                System.out.println(dictionary.get(n));
            }
            System.out.println(this.cod_bodegas_rutas);

            for (int n : this.cod_bodegas_rutas) {
                System.out.println(n);
            }
            SquaredPaper DrawWindow = new SquaredPaper();
            DrawWindow.cod_bodegas_rutas = this.cod_bodegas_rutas;
            DrawWindow.setSize(500, 500);
            DrawWindow.setResizable(true);
            DrawWindow.setLocation(200, 50);
            DrawWindow.setTitle("Pintando la ruta que viene de la BD");
            DrawWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            DrawWindow.setVisible(true);

        } catch (Exception e) {
            System.out.println((e));
            this.jDialog1.show();
            jDialog1.setSize(300, 200);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void campojpanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campojpanel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campojpanel1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.campojpanel1.setText("");
        this.campojpanel2.setText("");
        this.campojpanel3.setText("");
        this.campojpanel4.setText("");
        this.campojpanel5.setText("");
        this.jDialog1.hide();
    }//GEN-LAST:event_jButton2ActionPerformed


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.campojpanel1.setText("");
        this.campojpanel2.setText("");
        this.campojpanel3.setText("");
        this.campojpanel4.setText("");
        this.campojpanel5.setText("");
        this.jDialog2.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campojpanel1;
    private javax.swing.JTextField campojpanel2;
    private javax.swing.JTextField campojpanel3;
    private javax.swing.JTextField campojpanel4;
    private javax.swing.JTextField campojpanel5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label11;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    // End of variables declaration//GEN-END:variables
}
